### ISSUE TITLE
DFS: White-path theorem: possibly wrong statement

### ISSUE THREAD

**Issue by zzJinux** [sharmaeklavya2/theoremdep-source#3]
https://sharmaeklavya2.github.io/theoremdep/nodes/graph-theory/dfs/white-path-theorem.html

> $v$ is not a descendant of $u \implies u$ was already non-white when `visit(w)` was called. Therefore, $s(v) < s(w)$.

I couldn't get it why $s(v) < s(w)$ holds. Since $w$ is the predecessor of $v$ in the white path, it seems that $s(v) > s(w)$ is the case. Please let me know if I'm wrong. Besides the $s(v) < s(w)$, I also couldn't understand how “ $v$ is not a descendant of $u \implies u$ was already non-white when `visit(w)` was called ” holds.

**Comment by sharmaeklavya2** [comment]
Thanks for reporting this issue! I couldn't understand what I had written, so I rewrote the proof. Let me know if you still have issues with the proof.
